[package]
name = "volatile-bits"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "impl"
]


[dependencies]
volatile-bits-impl = { path = "./impl" }
anyhow = {version = "1.0.71", default-features = false}


[dev-dependencies]
trybuild2 = "1.0.2"
