[package]
name = "volatile-bits"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "macros"
]


[dependencies]
volatile-bits-macros = { path = "macros" }


[dev-dependencies]
trybuild2 = "1.0.2"
