[package]
name = "volatile-bits-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
syn = { version = "2.0.18", features = ["full", "extra-traits", "derive"] }
proc-macro2 = "1.0.59"
quote = "1.0.28"